"""autogenerated by genpy from crab_msgs/LegsJointsState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import crab_msgs.msg

class LegsJointsState(genpy.Message):
  _md5sum = "6fe1b620769e6858203cf2a048e48ef3"
  _type = "crab_msgs/LegsJointsState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """crab_msgs/LegJointsState[6] joints_state

================================================================================
MSG: crab_msgs/LegJointsState
float64[3] joint

"""
  __slots__ = ['joints_state']
  _slot_types = ['crab_msgs/LegJointsState[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joints_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LegsJointsState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.joints_state is None:
        self.joints_state = [crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState()]
    else:
      self.joints_state = [crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState(),crab_msgs.msg.LegJointsState()]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      for val1 in self.joints_state:
        buff.write(_struct_3d.pack(*val1.joint))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.joints_state is None:
        self.joints_state = None
      end = 0
      self.joints_state = []
      for i in range(0, 6):
        val1 = crab_msgs.msg.LegJointsState()
        start = end
        end += 24
        val1.joint = _struct_3d.unpack(str[start:end])
        self.joints_state.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      for val1 in self.joints_state:
        buff.write(val1.joint.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.joints_state is None:
        self.joints_state = None
      end = 0
      self.joints_state = []
      for i in range(0, 6):
        val1 = crab_msgs.msg.LegJointsState()
        start = end
        end += 24
        val1.joint = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
        self.joints_state.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d = struct.Struct("<3d")
