/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/ubuntu/catkin_ws/src/crab_msgs/srv/GetLegIKSolver.srv
 *
 */


#ifndef CRAB_MSGS_MESSAGE_GETLEGIKSOLVER_H
#define CRAB_MSGS_MESSAGE_GETLEGIKSOLVER_H

#include <ros/service_traits.h>


#include <crab_msgs/GetLegIKSolverRequest.h>
#include <crab_msgs/GetLegIKSolverResponse.h>


namespace crab_msgs
{

struct GetLegIKSolver
{

typedef GetLegIKSolverRequest Request;
typedef GetLegIKSolverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLegIKSolver
} // namespace crab_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crab_msgs::GetLegIKSolver > {
  static const char* value()
  {
    return "aab6d4778f2d7a09001d31408c116ed3";
  }

  static const char* value(const ::crab_msgs::GetLegIKSolver&) { return value(); }
};

template<>
struct DataType< ::crab_msgs::GetLegIKSolver > {
  static const char* value()
  {
    return "crab_msgs/GetLegIKSolver";
  }

  static const char* value(const ::crab_msgs::GetLegIKSolver&) { return value(); }
};


// service_traits::MD5Sum< ::crab_msgs::GetLegIKSolverRequest> should match 
// service_traits::MD5Sum< ::crab_msgs::GetLegIKSolver > 
template<>
struct MD5Sum< ::crab_msgs::GetLegIKSolverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crab_msgs::GetLegIKSolver >::value();
  }
  static const char* value(const ::crab_msgs::GetLegIKSolverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crab_msgs::GetLegIKSolverRequest> should match 
// service_traits::DataType< ::crab_msgs::GetLegIKSolver > 
template<>
struct DataType< ::crab_msgs::GetLegIKSolverRequest>
{
  static const char* value()
  {
    return DataType< ::crab_msgs::GetLegIKSolver >::value();
  }
  static const char* value(const ::crab_msgs::GetLegIKSolverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crab_msgs::GetLegIKSolverResponse> should match 
// service_traits::MD5Sum< ::crab_msgs::GetLegIKSolver > 
template<>
struct MD5Sum< ::crab_msgs::GetLegIKSolverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crab_msgs::GetLegIKSolver >::value();
  }
  static const char* value(const ::crab_msgs::GetLegIKSolverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crab_msgs::GetLegIKSolverResponse> should match 
// service_traits::DataType< ::crab_msgs::GetLegIKSolver > 
template<>
struct DataType< ::crab_msgs::GetLegIKSolverResponse>
{
  static const char* value()
  {
    return DataType< ::crab_msgs::GetLegIKSolver >::value();
  }
  static const char* value(const ::crab_msgs::GetLegIKSolverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAB_MSGS_MESSAGE_GETLEGIKSOLVER_H
