/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/ubuntu/catkin_ws/src/crab_msgs/msg/LegsJointsState.msg
 *
 */


#ifndef CRAB_MSGS_MESSAGE_LEGSJOINTSSTATE_H
#define CRAB_MSGS_MESSAGE_LEGSJOINTSSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <crab_msgs/LegJointsState.h>

namespace crab_msgs
{
template <class ContainerAllocator>
struct LegsJointsState_
{
  typedef LegsJointsState_<ContainerAllocator> Type;

  LegsJointsState_()
    : joints_state()  {
    }
  LegsJointsState_(const ContainerAllocator& _alloc)
    : joints_state()  {
      joints_state.assign( ::crab_msgs::LegJointsState_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::crab_msgs::LegJointsState_<ContainerAllocator> , 6>  _joints_state_type;
  _joints_state_type joints_state;




  typedef boost::shared_ptr< ::crab_msgs::LegsJointsState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crab_msgs::LegsJointsState_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct LegsJointsState_

typedef ::crab_msgs::LegsJointsState_<std::allocator<void> > LegsJointsState;

typedef boost::shared_ptr< ::crab_msgs::LegsJointsState > LegsJointsStatePtr;
typedef boost::shared_ptr< ::crab_msgs::LegsJointsState const> LegsJointsStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crab_msgs::LegsJointsState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crab_msgs::LegsJointsState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crab_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'crab_msgs': ['/home/ubuntu/catkin_ws/src/crab_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crab_msgs::LegsJointsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crab_msgs::LegsJointsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crab_msgs::LegsJointsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crab_msgs::LegsJointsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crab_msgs::LegsJointsState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crab_msgs::LegsJointsState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crab_msgs::LegsJointsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fe1b620769e6858203cf2a048e48ef3";
  }

  static const char* value(const ::crab_msgs::LegsJointsState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fe1b620769e6858ULL;
  static const uint64_t static_value2 = 0x203cf2a048e48ef3ULL;
};

template<class ContainerAllocator>
struct DataType< ::crab_msgs::LegsJointsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crab_msgs/LegsJointsState";
  }

  static const char* value(const ::crab_msgs::LegsJointsState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crab_msgs::LegsJointsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crab_msgs/LegJointsState[6] joints_state\n\
\n\
================================================================================\n\
MSG: crab_msgs/LegJointsState\n\
float64[3] joint\n\
";
  }

  static const char* value(const ::crab_msgs::LegsJointsState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crab_msgs::LegsJointsState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LegsJointsState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crab_msgs::LegsJointsState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crab_msgs::LegsJointsState_<ContainerAllocator>& v)
  {
    s << indent << "joints_state[]" << std::endl;
    for (size_t i = 0; i < v.joints_state.size(); ++i)
    {
      s << indent << "  joints_state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::crab_msgs::LegJointsState_<ContainerAllocator> >::stream(s, indent + "    ", v.joints_state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAB_MSGS_MESSAGE_LEGSJOINTSSTATE_H
